name: Update Estimate

on:
  schedule: 
    - cron: "0 5 * * *"
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up project requirements
        run: |
          pip install poetry
          poetry install
      - name: Run update script
        run: |
          poetry run ./update.py --skip-execute
        env:
          GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
